# Generated by Django 6.0.6 on 2026-06-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('channel', models.CharField(choices=[('system', 'اعلان داخل سایت'), ('sms', 'پیامک'), ('newsletter', 'خبرنامه')], max_length=16)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'در صف ارسال'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='queued', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('provider_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_outbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('info', 'اطلاع\u200cرسانی'), ('success', 'موفق'), ('warning', 'هشدار'), ('error', 'خطا')], default='info', max_length=16)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
