# Generated by Django 6.0.6 on 2026-06-17 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activity_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید فعالیت'),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, verbose_name='کد ملی/شناسه')),
                ('business_name', models.CharField(max_length=160, verbose_name='نام فارم/واحد فعالیت')),
                ('business_address', models.TextField(verbose_name='آدرس واحد فعالیت')),
                ('document', models.FileField(upload_to='verification-documents/', verbose_name='مدرک هویتی/فعالیت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
