# Generated by Django 6.0.6 on 2026-06-16 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('price', models.PositiveIntegerField()),
                ('unit', models.CharField(default='تومان', max_length=32)),
                ('direction', models.CharField(choices=[('up', 'افزایشی'), ('down', 'کاهشی'), ('flat', 'ثابت')], default='flat', max_length=8)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('immediate', 'فروش فوری'), ('future', 'فروش آتی')], default='immediate', max_length=16)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده')], default='active', max_length=16)),
                ('breed', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_chick', models.PositiveIntegerField()),
                ('province', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('delivery_date', models.DateField()),
                ('health_status', models.CharField(default='واکسینه شده', max_length=120)),
                ('parent_flock_age', models.CharField(default='۳۷-۵۰', max_length=32)),
                ('hatch_rate_percent', models.PositiveSmallIntegerField(default=84)),
                ('egg_weight_grams', models.PositiveSmallIntegerField(default=62)),
                ('vaccination_status', models.CharField(default='کامل', max_length=120)),
                ('reservation_percent', models.PositiveSmallIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('seller_name', models.CharField(blank=True, max_length=120)),
                ('seller_title', models.CharField(blank=True, max_length=120)),
                ('seller_rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('seller_transactions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'delivery_date', '-created_at'],
            },
        ),
    ]
