# Generated by Django 6.0.6 on 2026-06-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, upload_to='listing-images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('inactive', 'حذف شده')], default='active', max_length=16),
        ),
    ]
